In [144]:
# Import pandas and suppress warnings
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
cc_apps = pd.read_csv("cc_approvals.data", header=None)
cc_apps.head()

0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [145]:
print(cc_apps.describe())
print('\n')

print(cc_apps.info())
print('\n')

cc_apps.tail(17) # or cc_apps.sample()


               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 no

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [146]:
# Import numpy
import numpy as np

# Inspect missing values in the dataset
print(cc_apps.tail(17))

# Replace the '?'s with NaN
cc_apps = cc_apps.replace('?', np.nan)

# Inspect the missing values again
print(cc_apps.tail(17))


    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1

In [147]:
# Import numpy
import numpy as np

# Impute the missing values with mean imputation
cc_apps.loc[[2,7,10,14]] = cc_apps.loc[[2,7,10,14]].fillna(cc_apps.mean(numeric_only=True))


# Count the number of NaNs in the dataset to verify
print(cc_apps.isna().sum())

0     12
1     12
2      0
3      6
4      6
5      9
6      9
7      0
8      0
9      0
10     0
11     0
12     0
13    13
14     0
15     0
dtype: int64


In [148]:
# Import numpy
import numpy as np

# Iterate over each column of cc_apps
for col in cc_apps.columns:    
    # Check if the column is of object type    
    if cc_apps[col].dtypes == 'object':        
        # Impute with the most frequent value        
        cc_apps = cc_apps.fillna(cc_apps[col].value_counts().index[0])

# Count the number of NaNs in the dataset and print the counts to verify
print(cc_apps.isna().sum())


0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64


In [149]:
# Import LabelEncoder
from sklearn.preprocessing import LabelEncoder
# Instantiate LabelEncoder
le = LabelEncoder()
# Iterate over all the values of each column and extract their dtypes
for col in list(cc_apps):    
	# Compare if the dtype is object    
	if cc_apps[col].dtypes=='object':    
		# Use LabelEncoder to do the numeric transformation
            cc_apps[col]=le.fit_transform(cc_apps[col])


In [150]:
# Import train_test_split
from sklearn.model_selection import train_test_split

# Drop the features 11 and 13 and convert the DataFrame to a NumPy array
cc_apps = cc_apps.drop([11,13], axis=1)
cc_apps = cc_apps.values

# Segregate features and labels into separate variables
X,y = cc_apps[:,0:12] , cc_apps[:,13]

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(462, 12) (462,)
(228, 12) (228,)


In [151]:
# Import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Instantiate MinMaxScaler and use it to rescale X_train and X_test
scaler = MinMaxScaler(feature_range=(0, 1))

rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.fit_transform(X_test)

print(rescaledX_train.shape)
print(rescaledX_test.shape)


(462, 12)
(228, 12)


In [152]:
# Import LogisticRegression
from sklearn.linear_model import LogisticRegression

# Instantiate a LogisticRegression classifier with increased max_iter to avoid convergence warning
logreg = LogisticRegression(max_iter=1000)

# Fit logreg to the train set
logreg.fit(rescaledX_train,y_train)

LogisticRegression(max_iter=1000)

In [153]:
# Import confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Use logreg to predict instances from the test set and store it
y_pred = logreg.predict(rescaledX_test)

# Get the accuracy score of logreg model and print it
print("Accuracy of logistic regression classifier: ", accuracy_score(y_test,y_pred))

# Print the confusion matrix of the logreg model
print(confusion_matrix(y_test,y_pred))


Accuracy of logistic regression classifier:  0.8377192982456141
[[93 10]
 [27 98]]


In [154]:
# Import pandas
import pandas as pd
cc_apps = pd.read_csv("cc_approvals.data", header=None)
cc_apps.head()


0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [155]:
print(cc_apps.describe())
print('\n')

print(cc_apps.info())
print('\n')

cc_apps.tail(17) # or cc_apps.sample()


               2           7          10             14
count  690.000000  690.000000  690.00000     690.000000
mean     4.758725    2.223406    2.40000    1017.385507
std      4.978163    3.346513    4.86294    5210.102598
min      0.000000    0.000000    0.00000       0.000000
25%      1.000000    0.165000    0.00000       0.000000
50%      2.750000    1.000000    0.00000       5.000000
75%      7.207500    2.625000    3.00000     395.500000
max     28.000000   28.500000   67.00000  100000.000000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 no

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [156]:
from sklearn.model_selection import train_test_split

print(cc_apps.corr(numeric_only = True))

#Drop the features 11 and 13
cc_apps = cc_apps.drop([11, 13], axis=1)

# Split into train and test sets
cc_apps_train, cc_apps_test = train_test_split(cc_apps, test_size=0.33, random_state=42)


          2         7         10        14
2   1.000000  0.298902  0.271207  0.123121
7   0.298902  1.000000  0.322330  0.051345
10  0.271207  0.322330  1.000000  0.063692
14  0.123121  0.051345  0.063692  1.000000


In [157]:
# Import numpy
import numpy as np

# Replace the '?'s with NaN in the train and test sets
cc_apps_train = cc_apps_train.replace('?', np.nan)
cc_apps_test = cc_apps_test.replace('?', np.nan)

print(cc_apps_train)


      0      1      2    3    4    5    6       7  8  9   10 12    14 15
382    a  24.33  2.500    y    p    i   bb   4.500  f  f   0  g   456  -
137    b  33.58  2.750    u    g    m    v   4.250  t  t   6  g     0  +
346  NaN  32.25  1.500    u    g    c    v   0.250  f  f   0  g   122  -
326    b  30.17  1.085    y    p    c    v   0.040  f  f   0  g   179  -
33     a  36.75  5.125    u    g    e    v   5.000  t  f   0  g  4000  +
..   ...    ...    ...  ...  ...  ...  ...     ... .. ..  .. ..   ... ..
71     b  34.83  4.000    u    g    d   bb  12.500  t  f   0  g     0  -
106    b  28.75  1.165    u    g    k    v   0.500  t  f   0  s     0  -
270    b  37.58  0.000  NaN  NaN  NaN  NaN   0.000  f  f   0  p     0  +
435    b  19.00  0.000    y    p   ff   ff   0.000  f  t   4  g     1  -
102    b  18.67  5.000    u    g    q    v   0.375  t  t   2  g    38  -

[462 rows x 14 columns]


In [158]:
# Impute the missing values with mean imputation
cc_apps_train.fillna(cc_apps_train.mean(numeric_only = True), inplace=True)
cc_apps_test.fillna(cc_apps_train.mean(numeric_only=True), inplace=True)

# Count the number of NaNs in the datasets and print the counts to verify
print(cc_apps_train.isnull().sum())
print(cc_apps_test.isnull().sum())


0     8
1     5
2     0
3     6
4     6
5     7
6     7
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64
0     4
1     7
2     0
3     0
4     0
5     2
6     2
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64


In [159]:
for col in cc_apps_train.columns: # Iterate over each column of cc_apps_train

    if cc_apps_train[col].dtypes == 'object': # Check if the column is of object type
        # Impute with the most frequent value
        # The value_counts() function returns a Series that contain counts of unique values. It returns an object that will be in 
        # descending order so that its first element will be the most frequently-occurred element.
        cc_apps_train = cc_apps_train.fillna(cc_apps_train[col].value_counts().index[0])
        cc_apps_test = cc_apps_test.fillna(cc_apps_train[col].value_counts().index[0])

# Count the number of NaNs in the dataset and print the counts to verify
print(cc_apps_train.isnull().sum()) 
print(cc_apps_test.isnull().sum())
# At this point, there is no missing values.



0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
12    0
14    0
15    0
dtype: int64


In [160]:
# Convert the categorical features in the train and test sets independently
print(cc_apps_train)
cc_apps_train = pd.get_dummies(cc_apps_train) # try with argument dtype = int
cc_apps_test = pd.get_dummies(cc_apps_test)
print(cc_apps_train)
# Reindex the columns of the test set aligning with the train set
cc_apps_test = cc_apps_test.reindex(columns=cc_apps_train.columns, fill_value=0)


    0      1      2  3  4   5   6       7  8  9   10 12    14 15
382  a  24.33  2.500  y  p   i  bb   4.500  f  f   0  g   456  -
137  b  33.58  2.750  u  g   m   v   4.250  t  t   6  g     0  +
346  b  32.25  1.500  u  g   c   v   0.250  f  f   0  g   122  -
326  b  30.17  1.085  y  p   c   v   0.040  f  f   0  g   179  -
33   a  36.75  5.125  u  g   e   v   5.000  t  f   0  g  4000  +
..  ..    ...    ... .. ..  ..  ..     ... .. ..  .. ..   ... ..
71   b  34.83  4.000  u  g   d  bb  12.500  t  f   0  g     0  -
106  b  28.75  1.165  u  g   k   v   0.500  t  f   0  s     0  -
270  b  37.58  0.000  b  b   b   b   0.000  f  f   0  p     0  +
435  b  19.00  0.000  y  p  ff  ff   0.000  f  t   4  g     1  -
102  b  18.67  5.000  u  g   q   v   0.375  t  t   2  g    38  -

[462 rows x 14 columns]
         2       7  10    14    0_a    0_b  1_13.75  1_15.83  1_15.92  \
382  2.500   4.500   0   456   True  False    False    False    False   
137  2.750   4.250   6     0  False   True    Fal

In [161]:
# Import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Segregate features and labels into separate variables
# Note: Using ravel() to convert 2D array to 1D for sklearn classifiers
X_train = cc_apps_train.iloc[:, :-1].values
y_train = cc_apps_train.iloc[:, -1].values.ravel()
X_test = cc_apps_test.iloc[:, :-1].values
y_test = cc_apps_test.iloc[:, -1].values.ravel()

# Instantiate MinMaxScaler and use it to rescale X_train and X_test
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.transform(X_test)

In [162]:
# Import LogisticRegression
from sklearn.linear_model import LogisticRegression

# Instantiate a LogisticRegression classifier with increased max_iter to avoid convergence warning
logreg = LogisticRegression(max_iter=1000)

# Fit logreg to the train set
logreg.fit(rescaledX_train,y_train)

LogisticRegression(max_iter=1000)

In [163]:
# Import confusion_matrix
from sklearn.metrics import confusion_matrix

# Use logreg to predict instances from the test set and store it
y_pred = logreg.predict(rescaledX_test)

# Get the accuracy score of logreg model and print it
print("Accuracy of logistic regression classifier: ", logreg.score(rescaledX_test,y_test))

# Print the confusion matrix of the logreg model
confusion_matrix(y_test,y_pred)


Accuracy of logistic regression classifier:  1.0


array([[103,   0],
       [  0, 125]])

In [164]:
# Import KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

# Instantiate a KNN classifier with default parameter values
knn = KNeighborsClassifier()

# Fit knn to the train set
knn.fit(rescaledX_train, y_train)

# Use knn to predict instances from the test set
y_pred_knn = knn.predict(rescaledX_test)

# Get the accuracy score of knn model and print it
print("Accuracy of KNN classifier (k=5): ", knn.score(rescaledX_test, y_test))

# Print the confusion matrix of the knn model
print(confusion_matrix(y_test, y_pred_knn))

Accuracy of KNN classifier (k=5):  0.9254385964912281
[[ 95   8]
 [  9 116]]


In [165]:
# Finding the best k using Elbow Method
from matplotlib import pyplot as plt


error_rates = []
k_range = range(1, 41)

for k in k_range:
    knn_temp = KNeighborsClassifier(n_neighbors=k)
    knn_temp.fit(rescaledX_train, y_train)
    y_pred_temp = knn_temp.predict(rescaledX_test)
    error_rates.append(np.mean(y_pred_temp != y_test))

# Find the best k (minimum error rate)
best_k_elbow = k_range[np.argmin(error_rates)]

print(f"Best k using Elbow Method: {best_k_elbow}")

# Train KNN with best k from Elbow Method and evaluate
knn_elbow = KNeighborsClassifier(n_neighbors=best_k_elbow)
knn_elbow.fit(rescaledX_train, y_train)
y_pred_elbow = knn_elbow.predict(rescaledX_test)
accuracy_elbow = knn_elbow.score(rescaledX_test, y_test)

print(f"Accuracy with k={best_k_elbow} (Elbow Method): {accuracy_elbow:.4f}")

# Print the confusion matrix with best k from Elbow Method
print("\nConfusion Matrix with best k (Elbow Method):")
print(confusion_matrix(y_test, y_pred_elbow))

Best k using Elbow Method: 19
Accuracy with k=19 (Elbow Method): 0.9386

Confusion Matrix with best k (Elbow Method):
[[ 94   9]
 [  5 120]]


In [166]:
# Finding the best k using GridSearchCV (Cross-Validation)
from sklearn.model_selection import GridSearchCV

# Create a KNN classifier
knn_cv = KNeighborsClassifier()

# Create a dictionary of values for n_neighbors
param_grid = {'n_neighbors': range(1, 41)}

# Use GridSearchCV to find the best k using 5-fold cross-validation
knn_gscv = GridSearchCV(knn_cv, param_grid, cv=5, scoring='accuracy')
knn_gscv.fit(rescaledX_train, y_train)

# Get the best parameters and best score
best_k_cv = knn_gscv.best_params_['n_neighbors']
best_score_cv = knn_gscv.best_score_

print(f"Best k using GridSearchCV: {best_k_cv}")
print(f"Best cross-validation accuracy: {best_score_cv:.4f}")

# Evaluate on test set with best k
best_knn = KNeighborsClassifier(n_neighbors=best_k_cv)
best_knn.fit(rescaledX_train, y_train)
test_accuracy = best_knn.score(rescaledX_test, y_test)

print(f"Test set accuracy with k={best_k_cv}: {test_accuracy:.4f}")

# Print the confusion matrix with best k
y_pred_best_k = best_knn.predict(rescaledX_test)
print("\nConfusion Matrix with best k:")
print(confusion_matrix(y_test, y_pred_best_k))

Best k using GridSearchCV: 15
Best cross-validation accuracy: 0.9351
Test set accuracy with k=15: 0.9254

Confusion Matrix with best k:
[[ 93  10]
 [  7 118]]


In [167]:
param_grid = {'n_neighbors': np.arange(1, 11),
              'weights': ['uniform', 'distance'],
              'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
              'p': [1, 2]}

# Define the KNN classifier
knn = KNeighborsClassifier()

# Define the grid search object
grid = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')

# Fit the grid search to the training data before accessing results
grid.fit(rescaledX_train, y_train)

print("Best Hyperparameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)


Best Hyperparameters: {'algorithm': 'auto', 'n_neighbors': np.int64(10), 'p': 2, 'weights': 'distance'}
Best Accuracy: 0.9328658251519402
